### ISSUE TITLE
CORS error on pickle.view()

### ISSUE THREAD

**Issue by Maxson52** [souranalytics/pickle-js#2]
Using this client library throws the following CORS error on the initial `pickle.view()` request. 

I haven't gotten around to testing if this error occurs when using the fetch API (or axios) with CORS disabled, though I assume that's the solution.

`...has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Been wanting to try pickle for a while now so I look forward to giving it a second shot!

**Comment by alizahid** [comment]
Hey @Maxson52. I built this for a hackathon and sort of abandoned it since. I'm rebuilding it [here](https://github.com/souranalytics/souranalytics) and once it's ready, you can use that if you're interested.
